tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "bats-core"
brew "coreutils"
brew "duti"
brew "lotyp/formulae/dockutil"
brew "nano"
brew "stow"
brew "thefuck"
brew "tmux"
brew "topgrade"

# fs/network
brew "bat"
brew "croc"
brew "httpie"
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "wget"
brew "zoxide"

# search/grep/diff
brew "fd"
brew "fzf"
brew "git-delta"
brew "gnu-sed"
brew "grep"
brew "jq"
brew "psgrep"
brew "ripgrep"
brew "the_silver_searcher"

# languages/tools
brew "gh"
brew "n"
brew "python"
brew "ruby"
brew "rust"
brew "shellcheck"

# media
brew "ffmpeg"
brew "imagemagick"
brew "uni"
brew "webp"

# misc
brew "grip"

# My Dev Environment
brew "zellij"
brew "viu"

# nice to have
brew "lsd"
brew "dust"
brew "htop"

# mac app store (mas)
brew "mas"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "com.kagimacOS.Kagi-Search", id: 1622835804
mas "iA Writer", id: 775737590
mas "Things", id: 904280696
mas "Yoink", id: 457622435
